export const STATIC_ITEM_IDS: Record<string, number> = {
  'Item Cart Cannon': 0,
  'Item Cart Laser': 1,
  'Item Cart Medium': 2,
  'Item Cart Small': 3,
  'Item Drone Battery': 4,
  'Item Drone Feather': 5,
  'Item Drone Indestructible': 6,
  'Item Drone Torque': 7,
  'Item Drone Zero Gravity': 8,
  'Item Duck Bucket': 9,
  'Item Extraction Tracker': 10,
  'Item Grenade Duct Taped': 11,
  'Item Grenade Explosive': 12,
  'Item Grenade Human': 13,
  'Item Grenade Shockwave': 14,
  'Item Grenade Stun': 15,
  'Item Gun Handgun': 16,
  'Item Gun Laser': 17,
  'Item Gun Shockwave': 18,
  'Item Gun Shotgun': 19,
  'Item Gun Stun': 20,
  'Item Gun Tranq': 21,
  'Item Health Pack Large': 22,
  'Item Health Pack Medium': 23,
  'Item Health Pack Small': 24,
  'Item Leaf Blower': 25,
  'Item Melee Baseball Bat': 26,
  'Item Melee Frying Pan': 27,
  'Item Melee Inflatable Hammer': 28,
  'Item Melee Sledge Hammer': 28,
  'Item Melee Stun Baton': 29,
  'Item WalkieTalkieBox': 30,
  'Item Melee Sword': 31,
  'Item Mine Explosive': 32,
  'Item Mine Shockwave': 33,
  'Item Mine Stun': 34,
  'Item Orb Zero Gravity': 34,
  'Item Phase Bridge': 35,
  'Item Power Crystal': 36,
  'Item Rubber Duck': 37,
  'Item ReviveItem': 38,
  'Item Staff Torque': 40,
  'Item Staff Void': 41,
  'Item Staff Zero Gravity': 42,
  'Item Upgrade Death Head Battery': 43,
  'Item Upgrade Map Player Count': 44,
  'Item Upgrade Player Crouch Rest': 45,
  'Item Upgrade Player Energy': 46,
  'Item Upgrade Player Extra Jump': 47,
  'Item Upgrade Player Grab Range': 48,
  'Item Upgrade Player Grab Strength': 49,
  'Item Upgrade Player Health': 50,
  'Item Upgrade Player Sprint Speed': 51,
  'Item Upgrade Player Tumble Climb': 52,
  'Item Upgrade Player Tumble Launch': 53,
  'Item Upgrade Player Tumble Wings': 54,
  'Item Valuable Tracker': 55,
  'Item Vehicle Semiscooter': 56,
  'Item Vehicle Semiscooter Small': 57,
}
